openapi: 3.0.0
info:
  title: API Playground
  version: "1.0.0"
  description: >
    Public API used in Week 7 to explore URLs, HTTP,
    REST APIs, and client-server interaction.

servers:
  - url: https://api-swagger-playground.onrender.com/

paths:
  /users:
    get:
      summary: Get all users
      responses:
        "200":
          description: OK
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, age, year]
              properties:
                name: { type: string }
                email: { type: string }
                age: { type: integer }
                year: { type: integer }
      responses:
        "201":
          description: Created

  /users/year/{year}:
    get:
      summary: Get users by year
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
